from pacman103.core.mapper.partitioner_algorithms.basic_partitioner import BasicPartitioner
from pacman103.core.mapper.partitioner_algorithms.partition_and_place_partitioner import PartitionAndPlacePartitioner
